spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.175.128
    port: 5672
    username: admin
    password: admin  
  cloud:
    inetutils:
      ignored-interfaces:
        - VM.*
#      preferred-networks:
#        - 192.168.0    
server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/** 
    
zuul:
  retryable: true  
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  